/// Flutter icons Shop
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Shop
///      fonts:
///       - asset: fonts/Shop.ttf
///
/// 
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
///
import 'package:flutter/widgets.dart';

class Shop {
  Shop._();

  static const _kFontFam = 'Shop';
  static const String? _kFontPkg = null;

  static const IconData truck = IconData(0xf0d1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cart = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu = IconData(0xe871, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dice_d6 = IconData(0xf6d1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_right = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more_vert = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData local_shipping = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData barcode = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData barcode_1 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData barcodes = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}


class Barcode {
  Barcode._();

  static const _kFontFam = 'Barcode';
  static const String? _kFontPkg = null;

  static const IconData barcode_1 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData barcode = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}

